apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-read-pods
subjects:
  - kind: ServiceAccount
    name: devops
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: support
    apiGroup: rbac.authorization.k8s.io
roleRef:
    kind: ClusterRole
    name: cluster-pod-reader
    apiGroup: rbac.authorization.k8s.io