apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-finance
  namespace: finance
subjects:
  - kind: ServiceAccount
    name: accountant
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: finance-manager
  apiGroup: rbac.authorization.k8s.io