apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: secure-space
subjects:
  - kind: ServiceAccount
    name: devops
    apiGroup: rbac.authorization.k8s.io
roleRef:
    kind: Role
    name: secret-reader
    apiGroup: rbac.authorization.k8s.io